module.exports = {
  purge: ['./src/**/*.html', './src/**/*.vue'],
  theme: {
    extend: {
      fontFamily: {
        montserrat: ['Montserrat'],
        poppins: ['Poppins']
      },
      opacity: {
        5: '0.05',
        10: '0.1',
        30: '0.3'
      },
      colors: {
        primary: {
          accentLighter: '#DFEAFF',
          accentLight: '#B0CCFD',
          accent: '#4285F4',
          accentDarker: '#15489F',
          darkGray: '#606060',
          gray: '#A2A2A2',
          lightGray: '#BBBBBB',
          lighterGray: '#F5F5F5',
          yellow: '#F79F1A'
        },
        divider: '#DFE0EB'
      },
      fontSize: {
        31: '31px',
        30: '30px',
        25: '25px',
        17: '17px',
        15: '15px',
        16: '16px',
        14: '14px',
        13: '13px',
        50: '50px',
        10: '10px'
      },
      lineHeight: {
        180: '180%',
        150: '150%',
        130: '130%',
        120: '120%',
        100: '100%'
      },
      maxWidth: {
        '1/2': '50%',
        '1/3': '33.3%',
        '2/3': '66.6%',
        '1/4': '25%',
        '3/4': '75%',
        '1/5': '20%',
        '2/5': '40%',
        '3/5': '60%',
        '4/5': '80%',
        '1/7': '14.2857143%',
        '2/7': '28.5714286%',
        '3/7': '42.8571429%',
        '4/7': '57.1428571%',
        '5/7': '71.4285714%',
        '6/7': '85.7142857%'
      },
      maxHeight: {
        '1/4': '25%',
        '1/2': '50%',
        '3/4': '75%',
        '4/5': '80%',
        24: '6rem',
        96: '24rem'
      },
      minHeight: {
        15: '15vh',
        20: '20vh',
        30: '30vh',
        40: '40vh',
        50: '50vh',
        60: '60vh',
        70: '70vh',
        80: '80vh',
        90: '90vh'
      },
      minWidth: {
        20: '20vw',
        30: '30vw',
        40: '40vw',
        50: '50vw',
        60: '60vw'
      },
      spacing: {
        full: '100%',
        7: '1.75rem',
        9: '2.25rem',
        13: '3.25rem',
        '1/2': '50%',
        '1/3': '33.3%',
        '2/3': '66.6%',
        '1/4': '25%',
        '3/4': '75%',
        '1/5': '20%',
        '2/5': '40%',
        '3/5': '60%',
        '4/5': '80%',
        '1/7': '14.2857143%',
        '2/7': '28.5714286%',
        '3/7': '42.8571429%',
        '4/7': '57.1428571%',
        '5/7': '71.4285714%',
        '6/7': '85.7142857%',
        68: '17rem',
        72: '18rem',
        76: '19rem',
        78: '19.5rem',
        80: '20rem',
        84: '21rem',
        96: '24rem'
      },
      inset: {
        full: '100%',
        5: '.05rem',
        10: '.1rem',
        15: '.15rem',
        20: '.2rem',
        25: '.25rem',
        30: '.3rem',
        35: '.35rem',
        40: '.4rem',
        45: '.45rem',
        50: '.5rem',
        '-5': '-.05rem',
        '-10': '-.1rem',
        '-15': '-.15rem',
        '-20': '-.2rem',
        '-25': '-.25rem',
        '-30': '-.3rem',
        '-35': '-.35rem',
        '-40': '-.4rem',
        '-45': '-.45rem',
        '-50': '-.5rem'
      },
      screens: {
        xl: '1280px',
        xxl: '1441px',
        xxxl: '2560px',
        'md-h': { raw: '(max-height: 767px)' },
        'lg-h': { raw: '(min-height: 768px) and (max-height : 1024px)' },
        'xl-h': { raw: '(min-height: 1024px)' }
      }
    }
  },
  variants: {
    appearance: ['responsive'],
    backgroundAttachment: ['responsive'],
    backgroundColor: ['responsive', 'hover', 'focus'],
    backgroundPosition: ['responsive'],
    backgroundRepeat: ['responsive'],
    backgroundSize: ['responsive'],
    borderCollapse: [],
    borderColor: ['responsive', 'hover', 'focus'],
    borderRadius: ['responsive'],
    borderStyle: ['responsive'],
    borderWidth: ['responsive'],
    cursor: ['responsive'],
    display: ['responsive', 'group-hover'],
    flexDirection: ['responsive'],
    flexWrap: ['responsive'],
    alignItems: ['responsive'],
    alignSelf: ['responsive'],
    justifyContent: ['responsive'],
    alignContent: ['responsive'],
    flex: ['responsive'],
    flexGrow: ['responsive'],
    flexShrink: ['responsive'],
    float: ['responsive'],
    fontFamily: ['responsive'],
    fontWeight: ['responsive', 'hover', 'focus'],
    height: ['responsive'],
    lineHeight: ['responsive'],
    listStylePosition: ['responsive'],
    listStyleType: ['responsive'],
    margin: ['responsive'],
    maxHeight: ['responsive'],
    maxWidth: ['responsive'],
    minHeight: ['responsive'],
    minWidth: ['responsive'],
    negativeMargin: ['responsive'],
    objectFit: ['responsive'],
    objectPosition: ['responsive'],
    opacity: ['responsive'],
    outline: ['focus'],
    overflow: ['responsive'],
    padding: ['responsive'],
    pointerEvents: ['responsive'],
    position: ['responsive'],
    inset: ['responsive'],
    resize: ['responsive'],
    boxShadow: ['responsive', 'hover', 'focus'],
    fill: [],
    stroke: [],
    tableLayout: ['responsive'],
    textAlign: ['responsive'],
    textColor: ['responsive', 'hover', 'focus'],
    fontSize: ['responsive'],
    fontStyle: ['responsive'],
    textTransform: ['responsive'],
    textDecoration: ['responsive', 'hover', 'focus'],
    fontSmoothing: ['responsive'],
    letterSpacing: ['responsive'],
    userSelect: ['responsive'],
    verticalAlign: ['responsive'],
    visibility: ['responsive', 'hover', 'group-hover'],
    whitespace: ['responsive'],
    wordBreak: ['responsive'],
    width: ['responsive'],
    zIndex: ['responsive']
  },
  corePlugins: {
    container: false
  },
  plugins: []
}
